moderntribe/wme

- src/components/button/button.stories.tsx
- src/components/progress-bar/progress-bar.stories.tsx
- src/components/setup-card-header/setup-card-header.stories.tsx
- src/components/setup-card-task/setup-card-task.stories.tsx
- src/components/setup-card-task/setup-card-task.tsx
- src/components/setup-card/setup-card.stories.mdx
- src/theme/theme.ts
- Provides mechanism to disable Task and Action in the SetupCardTask component
- Updates Stories to show disabled Tasks and Actions
- Adds disabled primary button story
> [FRAME-18] QA Fixes and Disabled Task Options

- src/components/chip/chip.stories.tsx
- src/components/chip/chip.tsx
- src/components/chip/index.ts
- src/components/index.ts
- src/components/progress-bar/progress-bar.stories.tsx
- src/components/setup-card-chip/index.ts
- src/components/setup-card-footer/setup-card-footer.stories.tsx
- src/components/setup-card-header/setup-card-header.stories.tsx
- src/components/setup-card-list-item/setup-card-list-item.stories.tsx
- src/components/setup-card-list/setup-card-list.stories.tsx
- src/components/setup-card-task/setup-card-task.stories.tsx
- src/components/setup-card/setup-card.stories.mdx
- src/components/tooltip/index.ts
- src/components/tooltip/tooltip.stories.tsx
- src/components/tooltip/tooltip.tsx
- src/theme/theme.ts
https://moderntribe.atlassian.net/browse/FRAME-14
- build out tooltips
- organize components into sub categories
- rename SetupCardChip to Chip
- clean up comments from original scaffolding 
http://p.tri.be/jUFk0e
> Tooltips + component organizing

- src/components/checkbox/checkbox.stories.tsx
- src/components/checkbox/checkbox.tsx
- src/components/dropdown/dropdown.stories.tsx
- src/components/dropdown/dropdown.tsx
- src/components/error-text/error-text.tsx
- src/components/error-text/index.ts
- src/components/file-upload/file-upload.tsx
- src/components/form-control-label/form-control-label.tsx
- src/components/form-helper-text/form-helper-text.tsx
- src/components/index.ts
- src/components/menu-item/menu-item.tsx
- src/components/nav-number/nav-number.tsx
- src/components/navigation/navigation.stories.mdx
- src/components/navigation/navigation.tsx
- src/components/password-field/password-field.stories.tsx
- src/components/password-field/password-field.tsx
- src/components/radio-button-group/radio-button-group.stories.tsx
- src/components/radio-button-group/radio-button-group.tsx
- src/components/setup-card-list/setup-card-list.stories.tsx
- src/components/setup-card-task/setup-card-task.tsx
- src/components/split-button/split-button.tsx
- src/components/text-field/text-field.stories.tsx
- src/components/text-field/text-field.tsx
https://moderntribe.atlassian.net/browse/FRAME-30
- adding error messages to:
-- checkbox
-- dropdown
-- file upload
-- password
-- radio button group
-- text field
- errors should show above helper text and display as red
- new ErrorText component
- changing commas to semi colons in interfaces (thanks TS)
- fixing import semantics
- http://p.tri.be/8gAwWL
> Error Messages + Code Cleanup

- src/components/index.ts
- src/components/setup-card/setup-card.stories.mdx
- src/components/video-embed/index.ts
- src/components/video-embed/video-embed.stories.mdx
- src/components/video-embed/video-embed.tsx
- https://moderntribe.atlassian.net/browse/FRAME-24
- video embed component
- height and width are handled with CSS, made it much easier to work within a layout. verified it's ok for iFrame not to have width and height attributes
http://p.tri.be/QIRz0n
> Video Embed

- src/components/card-select-item/card-select-item.tsx
- src/components/setup-card-footer/setup-card-footer.stories.mdx
- src/components/setup-card-header/setup-card-header.stories.mdx
- src/components/setup-card-list-item/setup-card-list-item.stories.mdx
- src/components/setup-card-list-item/setup-card-list-item.tsx
- src/components/setup-card-list/setup-card-list.stories.mdx
- src/components/setup-card-task/setup-card-task.stories.mdx
- src/components/setup-card/setup-card.stories.mdx
Various Setup Card documentation!
> [FRAME-19] Setup Card Documentation

- src/components/wizard-footer/wizard-footer.stories.mdx
- src/components/wizard-footer/wizard-footer.tsx
- couple small fixes needed to get the stepper/routing working in SB
- add loading button
> Wizard Footer/Stepper Fixes

- src/components/form-control-label/form-control-label.tsx
- src/components/wizard-footer/wizard-footer.stories.mdx
- src/components/wizard-footer/wizard-footer.tsx
- small wizard tweaks for matching SB footer
- left align form control label
> Wizard Fixes

- package-lock.json
- package.json
- src/components/wizard-footer/wizard-footer.tsx
- src/components/wizard/wizard.tsx
- fix bug in footer with disableAll
- change footer positioning to fixed
- version bump to 0.1.13
> Bug Fixes, Footer Positioning

- src/components/wizard-footer/wizard-footer.tsx
- fix for skip button
- adds class for last step button for SB
> Footer Fixes + additional class

- package.json
- src/components/index.ts
- src/components/setup-card-content/index.ts
- src/components/setup-card-content/setup-card-content.tsx
- src/components/setup-card-header/setup-card-header.tsx
- src/components/setup-card-task/setup-card-task.tsx
- src/components/setup-card/setup-card.stories.mdx
- src/index.ts
- New SetupCardContent component
- Various tweaks for Setup Cards
> [WME-224] Various Fixes for Setup Cards

- src/components/exit-button/exit-button.tsx
- src/components/wizard-section-title/wizard-section-title.tsx
- small style changes for the section title component
- standardizes line height for section title
- creates new styled component so we can style the text using styleOverrides
> Section Title Fixes

- src/components/setup-card-task/setup-card-task.stories.mdx
- src/components/setup-card-task/setup-card-task.tsx
- src/components/setup-card/setup-card.stories.mdx
- Updates SetupCardTask to be more flexible and intuitive.
- Updates SetupCard and SetupCardTask stories to reflect changes.
Here's a screenshot of the the diff when updating StoreBuilder to use the refactored component: http://p.tri.be/lOHm1J
> SetupCardTask Refactor and Stories Updated

- src/components/select-input/select-input.tsx
- src/components/setup-card-task/setup-card-task.tsx
- src/components/wizard/wizard.stories.mdx
- [Replace legacy form components](https://github.com/moderntribe/wme/commit/b6a45fda0ea5f27d872202e2114a7f886722c719)
- [Fix linting errors](https://github.com/moderntribe/wme/commit/e2a140faf1602de17ab7e1a79132f903717ae23a)
> Fix storybook build errors

- package.json
- src/components/wizard-footer/wizard-footer.tsx
- Provides support for disabling the Step navigator on a per-step basis
- Bumps package version
> Adds support for disabling step buttons

- package.json
- src/components/file-upload-header/file-upload-header.tsx
- src/components/file-upload-select/file-upload-select.tsx
Fix FileUpload linter issues and bump package version
> Fix FileUpload linter issues and bump package version

- package.json
- src/components/exit-button/exit-button.tsx
- src/components/wizard-section-title/wizard-section-title.tsx
- add color property to section title heading
- add font-weight to exit button
> Section Title Heading Fix + Exit Button FIx

- package.json
- src/components/card-select-item/card-select-item.tsx
- Increases margin-bottom value on icon element to provide more space between it and the card's title element.
- Bumps package version
> CardSelect Spacing Change

- package.json
- src/components/exit-button/exit-button.tsx
- src/components/index.ts
- src/components/logo/logo.tsx
- src/components/setup-card-accordion/index.ts
- src/components/setup-card-accordion/setup-card-accordion.tsx
- src/components/setup-card-footer/setup-card-footer.stories.mdx
- src/components/setup-card-info-row/setup-card-info-row.tsx
- src/components/setup-card-task/index.ts
- src/components/setup-card-task/setup-card-task.tsx
- src/components/text-input/text-input.tsx
- src/components/wizard-section-title/wizard-section-title.tsx
- src/components/wizard/wizard.tsx
- Adds new `SetupCardAccordion` component for use in `SetupCardFooter`.
- Lint fixes
- Adjustments as required during implementation w/in Sitebuilder project.
> [SITE-9] Adjustments, Cleanup and Additions

- pnpm-lock.yaml
Fixes multiple React error by making WME-UI use the same React version as Store and SiteBuilder packages.
> Update WME UI React versions to match Store/SiteBuilder

- .changeset/twenty-years-run.md
- packages/wme-ui/src/components/wizard-section-title/wizard-section-title.tsx
When the component is `bookend=true`, we'll add `isBookend` className to elements w/in the `WizardSectionTitle` component. This provides us the opportunity to target and style conditionally.
> Add 'isBookend' className to WizardSectionTitle

- .changeset/thin-dingos-enjoy.md
- packages/sitebuilder/package.json
- packages/sitebuilder/src/contexts/WizardProvider.tsx
- packages/sitebuilder/src/utils/handleTelemetryRequest.ts
- packages/sitebuilder/src/utils/index.ts
- packages/sitebuilder/tsconfig.json
- packages/storebuilder/package.json
- packages/storebuilder/src/constants/index.ts
- packages/storebuilder/src/contexts/WizardProvider.tsx
- packages/storebuilder/src/utils/handleTelemetryRequest.ts
- packages/storebuilder/src/utils/index.ts
- packages/storebuilder/src/wizards/payments/paypal/screens/Success.tsx
- packages/storebuilder/src/wizards/payments/stripe/screens/Success.tsx
- packages/storebuilder/tsconfig.json
- pnpm-lock.yaml
-https://moderntribe.atlassian.net/browse/SITE-35
- Makes AJAX request when a wizard is started
- Makes AJAX request when PayPal or Stripe are completed (the rest are completed by the backend)
Note: my local wanted me to install the webpack-cli, but I can remove that from this PR if needed. It's just a dev dependency though, so I figure it may be needed by other devs as well.
> Telemetry Started/Completed

- .changeset/strange-toes-hug.md
- packages/sitebuilder/src/setup/SetupCard.tsx
- packages/wme-ui/src/components/chip/chip.tsx
- Adjusts text and icon color for Chip.
- Adds correct implementation of Chip for SiteBuilder Setup page.
> [SITE-7] Fix for Chip

- .changeset/makeup-change-message.md
Adds changeset for previously-merged branch
> Adds changeset for previous commit

- .changeset/loud-cheetahs-rule.md
- packages/sitebuilder/src/contexts/LookAndFeelProvider.tsx
- packages/sitebuilder/src/wizards/look-and-feel/LookAndFeelWizard.tsx
- packages/sitebuilder/src/wizards/look-and-feel/data/look-and-feel-screen-data.tsx
- packages/storebuilder/src/wizards/payments/paypal/PaymentsPaypalWizard.tsx
- packages/storebuilder/src/wizards/payments/stripe/PaymentsStripeWizard.tsx
- https://moderntribe.atlassian.net/browse/SITE-52
- https://moderntribe.atlassian.net/browse/SITE-53
- Disable next button if no template selected.
- Fix delete content warning showing on first time through
- Check for response from oauth and throw error if response is empty
> Template Bug Fix + Oauth response FE check 

- .changeset/makeup-changes-tribe.md
- updates changeset for previous PR on this same branch
> Update changeset for L&F complete screen

- .changeset/dry-feet-smile.md
- packages/sitebuilder/src/wizards/look-and-feel/screens/Complete.tsx
A prop changed on the backend. This change will reflect that update.
> Fix L&F Complete Screen prop

- .changeset/two-falcons-beg.md
- packages/storebuilder/src/wizards/store-setup/data/constants.ts
Replaces lorem ipsum text on final Store Setup screen with true content.
> [SITE-71] Replace placeholder text

- packages/storebuilder/mix-manifest.json
- packages/wme-ui/src/components/card-select-group/card-select-group.tsx
- packages/wme-ui/src/components/card-select-item/card-select-item.tsx
- packages/wme-ui/src/components/checkbox-input/checkbox-input.tsx
- packages/wme-ui/src/components/list-item-checkout/list-item-checkout.tsx
- packages/wme-ui/src/components/radio-group/radio-group.tsx
- packages/wme-ui/src/components/setup-card-footer/setup-card-footer.tsx
- packages/wme-ui/src/components/setup-card-list-item/setup-card-list-item.tsx
- packages/wme-ui/src/components/wizard-footer/wizard-footer.tsx
- packages/wme-ui/src/theme/theme.ts
[SITE-80](https://moderntribe.atlassian.net/browse/SITE-80)
Updated the theme to work with Nexcess colors and tweaked a few components.
Notable changes:
- Update MuiLink with a global change to use `theme.palette.text.link` color
> [SITE-80] Update Framework theme

- packages/wme-ui/src/components/index.ts
- packages/wme-ui/src/components/jump-nav/index.ts
- packages/wme-ui/src/components/jump-nav/jump-nav.stories.mdx
- packages/wme-ui/src/components/jump-nav/jump-nav.tsx
[SITE-119](https://moderntribe.atlassian.net/browse/SITE-119)
This PR adds the Jump Nav component and its corresponding story into the WME Framework.
> Jump nav component and story

- .changeset/violet-crabs-enjoy.md
- packages/sitebuilder/src/wizards/go-live/data/constants.ts
- packages/sitebuilder/src/wizards/go-live/screens/ClaimYourDomain.tsx
- Updates copy for the return screen seen after domain purchase.
- Changes paragraph from `body1` to `body2` variant to match design.
> Copy update  on ClaimYourDomain.tsx

- plugins/wme-sitebuilder/composer.json
- plugins/wme-sitebuilder/composer.lock
- Match the Stripe plugin to the currently supported [version](https://github.com/moderntribe/wme/blob/d22e8d4cb165aa2bf1364587f8965fb087976a48/plugins/wme-sitebuilder/wme-sitebuilder/Plugins/PaymentGateways/Stripe.php#L29) for the Gateway.
- Match the PayPal plugin to the currently supported [version](https://github.com/moderntribe/wme/blob/d22e8d4cb165aa2bf1364587f8965fb087976a48/plugins/wme-sitebuilder/wme-sitebuilder/Plugins/PaymentGateways/PayPal.php#L28) for the Gateway.
> Match currently installed plugins to their supported gateway versions

- packages/storebuilder/.eslintrc.json
- packages/storebuilder/src/logos/index.ts
- packages/storebuilder/src/setup/SetupCard.tsx
- packages/storebuilder/src/setup/SetupScreen.tsx
- packages/storebuilder/src/setup/data/constants.ts
Updated Storebuilder with the most up-to-date styles. Very few changes, but there are some removals to accommodate the "less is more" design style that's being used now.
There are a few changes in the [Figma](https://www.figma.com/file/3DnmLW3jTWuxLVKBjQWv5c/Cloud-Platform-1.0?node-id=6214%3A9642&t=UYhnvNxQm0SYg5YJ-0) that requires backend data changes.
> Update Storebuilder with newest styles

- .changeset/ten-socks-hug.md
- .github/workflows/ci.yml
- packages/sitebuilder/src/contexts/DomainConnectProvider.tsx
- packages/sitebuilder/src/wizards/go-live/domain-connect/screens/VerifyDomain.tsx
- packages/sitebuilder/src/wizards/go-live/partials/ErrorDomainRegisteredNotPointing.tsx
Domain connect state was off and causing undesired behavior in the feature. Part of this had do with a miss during our refactor late 2022, but additionally we'd missed some necessary state management.
This PR fixes the screen state data miss and provides more explicit state management of the domain connect screens.
> [WME-288] Domain Verification Fix

- plugins/wme-sitebuilder/wme-sitebuilder/Cards/Shipping.php
- plugins/wme-sitebuilder/wme-sitebuilder/Plugins/Shipping.php
- Adding buttons to the shipping card instead of arrow links
- Changing the card footer with helper links
> chore: Revising shipping card look and footer

- packages/site-settings/site-settings.d.ts
- packages/site-settings/src/setup/SetupCards.tsx
- packages/site-settings/src/setup/cards/SiteVisibility.tsx
- packages/wme-ui/src/components/chip/chip.tsx
- plugins/wme-sitebuilder/wme-sitebuilder/Cards/SiteVisibility.php
- plugins/wme-sitebuilder/wme-sitebuilder/Container.php
- Site visibility card added to the site settings screen
- Background and text color changes happened on the `wme-ui chip` component
> chore: Adding Site Visibility card into the site settings package

- plugins/wme-sitebuilder/wme-sitebuilder/Cards/Shipping.php
- plugins/wme-sitebuilder/wme-sitebuilder/Container.php
- plugins/wme-sitebuilder/wme-sitebuilder/Plugins/Shipping.php
Payment Gateway installations were swapped over in #204. This PR handles the switch for the Shipping Plugin to use the PluginInstaller.
> [SITE-201] Use the PluginInstaller to handle installing and activating the USPS Shipping Plugin

- packages/sitebuilder/src/setup/SetupScreen.tsx
> chore: Removing jump nav on site setup page

- packages/sitebuilder/src/wizards/first-time-configuration/components/CustomSelectInput.tsx
- packages/sitebuilder/src/wizards/first-time-configuration/data/constants.ts
- packages/sitebuilder/src/wizards/first-time-configuration/screens/ContentTone.tsx
- packages/wme-ui/src/components/autocomplete/autocomplete.tsx
- packages/wme-ui/src/components/chips-input/chips-input.tsx
- Update the Autocomplete component to look more like the design
- Update the delete button on the Chip in the Chips-Input
- Update the Custom Select Input (not used at this point)
- Change the content personality select box from custom select to standard select.
> Small polish fixes for beta

- packages/sitebuilder/src/hooks/useKadencePages.ts
- packages/sitebuilder/src/wizards/first-time-configuration/screens/StyleSelection.tsx
Update the site template selection to show each template with the 8 style palettes we currently have.
> Adding each style palette to each template

- .changeset/wicked-seahorses-grin.md
- .github/workflows/split.yml
- plugins/wme-sitebuilder/wme-sitebuilder/Cards/SiteContent.php
- plugins/wme-sitebuilder/wme-sitebuilder/Plugins/PaymentGateways/PayPal.php
Brings in all recent bug fixes to main.
> Chore: combine bugfixes
